In [1]:
import os
import warnings

import pandas as pd
import numpy as np

warnings.filterwarnings("ignore")

In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)

In [3]:
BASE_DIR = os.path.abspath(os.path.join(os.getcwd(), ".."))

RAW_DATA_PATH = os.path.join(
    BASE_DIR,
    "data",
    "raw",
    "owid-covid-data (1).csv"
)

PROCESSED_DATA_PATH = os.path.join(
    BASE_DIR,
    "data",
    "processed",
    "cleaned_covid_data.csv"
)

print("Raw Dataset Path:")
print(RAW_DATA_PATH)

print("\nProcessed Dataset Path:")
print(PROCESSED_DATA_PATH)

Raw Dataset Path:
C:\Users\roshi\Downloads\covid19-data-analysis-visualization-main\covid19-data-analysis-visualization-main\data\raw\owid-covid-data (1).csv

Processed Dataset Path:
C:\Users\roshi\Downloads\covid19-data-analysis-visualization-main\covid19-data-analysis-visualization-main\data\processed\cleaned_covid_data.csv

In [5]:
df = pd.read_csv(RAW_DATA_PATH)

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [6]:
print(df.shape)

df.head()

(44785, 41)

  iso_code continent     location        date  total_cases  new_cases  new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  total_cases_per_million  new_cases_per_million  new_cases_smoothed_per_million  total_deaths_per_million  new_deaths_per_million  new_deaths_smoothed_per_million  new_tests  total_tests  total_tests_per_thousand  new_tests_per_thousand  new_tests_smoothed  new_tests_smoothed_per_thousand  tests_per_case  positive_rate tests_units  stringency_index  population  population_density  median_age  aged_65_older  aged_70_older  gdp_per_capita  extreme_poverty  cardiovasc_death_rate  diabetes_prevalence  female_smokers  male_smokers  handwashing_facilities  hospital_beds_per_thousand  life_expectancy  human_development_index
0      AFG      Asia  Afghanistan  2019-12-31          0.0        0.0                 NaN           0.0         0.0                  NaN                      0.0                    0.0                             NaN                       0.0                     0.0                              NaN        NaN          NaN                       NaN                     NaN                 NaN                              NaN             NaN            NaN         NaN               NaN  38928341.0              54.422        18.6          2.581          1.337        1803.987              NaN                597.029                 9.59             NaN           NaN                  37.746                         0.5            64.83                    0.498
1      AFG      Asia  Afghanistan  2020-01-01          0.0        0.0                 NaN           0.0         0.0                  NaN                      0.0                    0.0                             NaN                       0.0                     0.0                              NaN        NaN          NaN                       NaN                     NaN                 NaN                              NaN             NaN            NaN         NaN               0.0  38928341.0              54.422        18.6          2.581          1.337        1803.987              NaN                597.029                 9.59             NaN           NaN                  37.746                         0.5            64.83                    0.498
2      AFG      Asia  Afghanistan  2020-01-02          0.0        0.0                 NaN           0.0         0.0                  NaN                      0.0                    0.0                             NaN                       0.0                     0.0                              NaN        NaN          NaN                       NaN                     NaN                 NaN                              NaN             NaN            NaN         NaN               0.0  38928341.0              54.422        18.6          2.581          1.337        1803.987              NaN                597.029                 9.59             NaN           NaN                  37.746                         0.5            64.83                    0.498
3      AFG      Asia  Afghanistan  2020-01-03          0.0        0.0                 NaN           0.0         0.0                  NaN                      0.0                    0.0                             NaN                       0.0                     0.0                              NaN        NaN          NaN                       NaN                     NaN                 NaN                              NaN             NaN            NaN         NaN               0.0  38928341.0              54.422        18.6          2.581          1.337        1803.987              NaN                597.029                 9.59             NaN           NaN                  37.746                         0.5            64.83                    0.498
4      AFG      Asia  Afghanistan  2020-01-04          0.0        0.0                 NaN           0.0         0.0                  NaN                      0.0                    0.0                             NaN                       0.0                     0.0                              NaN        NaN          NaN                       NaN                     NaN                 NaN                              NaN             NaN            NaN         NaN               0.0  38928341.0              54.422        18.6          2.581          1.337        1803.987              NaN                597.029                 9.59             NaN           NaN                  37.746                         0.5            64.83                    0.498

In [7]:
print(df.columns.tolist())

['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases', 'new_cases_smoothed', 'total_deaths', 'new_deaths', 'new_deaths_smoothed', 'total_cases_per_million', 'new_cases_per_million', 'new_cases_smoothed_per_million', 'total_deaths_per_million', 'new_deaths_per_million', 'new_deaths_smoothed_per_million', 'new_tests', 'total_tests', 'total_tests_per_thousand', 'new_tests_per_thousand', 'new_tests_smoothed', 'new_tests_smoothed_per_thousand', 'tests_per_case', 'positive_rate', 'tests_units', 'stringency_index', 'population', 'population_density', 'median_age', 'aged_65_older', 'aged_70_older', 'gdp_per_capita', 'extreme_poverty', 'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers', 'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand', 'life_expectancy', 'human_development_index']

In [8]:
df.columns = [
    col.strip().lower()
    for col in df.columns
]

print(df.columns.tolist())

['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases', 'new_cases_smoothed', 'total_deaths', 'new_deaths', 'new_deaths_smoothed', 'total_cases_per_million', 'new_cases_per_million', 'new_cases_smoothed_per_million', 'total_deaths_per_million', 'new_deaths_per_million', 'new_deaths_smoothed_per_million', 'new_tests', 'total_tests', 'total_tests_per_thousand', 'new_tests_per_thousand', 'new_tests_smoothed', 'new_tests_smoothed_per_thousand', 'tests_per_case', 'positive_rate', 'tests_units', 'stringency_index', 'population', 'population_density', 'median_age', 'aged_65_older', 'aged_70_older', 'gdp_per_capita', 'extreme_poverty', 'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers', 'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand', 'life_expectancy', 'human_development_index']

In [ ]:
COLUMN_MAPPING = {
    "location": "country",
    "entity": "country",
    "day": "date",
    "cases": "new_cases",
    "deaths": "new_deaths",
    "vaccinations": "total_vaccinations",
}

for old_col, new_col in COLUMN_MAPPING.items():

    if old_col in df.columns:

        df.rename(
            columns={old_col: new_col},
            inplace=True
        )

print(df.columns.tolist())

['iso_code', 'continent', 'country', 'date', 'total_cases', 'new_cases', 'new_cases_smoothed', 'total_deaths', 'new_deaths', 'new_deaths_smoothed', 'total_cases_per_million', 'new_cases_per_million', 'new_cases_smoothed_per_million', 'total_deaths_per_million', 'new_deaths_per_million', 'new_deaths_smoothed_per_million', 'new_tests', 'total_tests', 'total_tests_per_thousand', 'new_tests_per_thousand', 'new_tests_smoothed', 'new_tests_smoothed_per_thousand', 'tests_per_case', 'positive_rate', 'tests_units', 'stringency_index', 'population', 'population_density', 'median_age', 'aged_65_older', 'aged_70_older', 'gdp_per_capita', 'extreme_poverty', 'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers', 'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand', 'life_expectancy', 'human_development_index', 'new_vaccinations']

In [13]:
required_columns = [
    "country",
    "date",
    "new_cases",
    "new_deaths",
    "total_vaccinations",
]

for col in required_columns:

    if col not in df.columns:

        print(f"{col} --> MISSING")

    else:

        print(f"{col} --> PRESENT")

country --> PRESENT
date --> PRESENT
new_cases --> PRESENT
new_deaths --> PRESENT
total_vaccinations --> MISSING

In [14]:
for col in required_columns:

    if col not in df.columns:

        if col == "country":

            df[col] = "Unknown"

        elif col == "date":

            df[col] = pd.NaT

        else:

            df[col] = 0

print(df.columns.tolist())

['iso_code', 'continent', 'country', 'date', 'total_cases', 'new_cases', 'new_cases_smoothed', 'total_deaths', 'new_deaths', 'new_deaths_smoothed', 'total_cases_per_million', 'new_cases_per_million', 'new_cases_smoothed_per_million', 'total_deaths_per_million', 'new_deaths_per_million', 'new_deaths_smoothed_per_million', 'new_tests', 'total_tests', 'total_tests_per_thousand', 'new_tests_per_thousand', 'new_tests_smoothed', 'new_tests_smoothed_per_thousand', 'tests_per_case', 'positive_rate', 'tests_units', 'stringency_index', 'population', 'population_density', 'median_age', 'aged_65_older', 'aged_70_older', 'gdp_per_capita', 'extreme_poverty', 'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers', 'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand', 'life_expectancy', 'human_development_index', 'new_vaccinations', 'total_vaccinations']

In [15]:
df["date"] = pd.to_datetime(
    df["date"],
    errors="coerce"
)

print(df["date"].head())

0   2019-12-31
1   2020-01-01
2   2020-01-02
3   2020-01-03
4   2020-01-04
Name: date, dtype: datetime64[ns]

In [16]:
initial_shape = df.shape

df = df[
    df["date"].notna()
]

final_shape = df.shape

print("Before Removing Invalid Dates:", initial_shape)

print("After Removing Invalid Dates:", final_shape)

Before Removing Invalid Dates: (44785, 43)
After Removing Invalid Dates: (44785, 43)

In [17]:
df.isnull().sum()

iso_code                             264
continent                            528
country                                0
date                                   0
total_cases                          603
new_cases                            803
new_cases_smoothed                  1585
total_deaths                         603
new_deaths                           803
new_deaths_smoothed                 1585
total_cases_per_million              867
new_cases_per_million                867
new_cases_smoothed_per_million      1650
total_deaths_per_million             867
new_deaths_per_million               867
new_deaths_smoothed_per_million     1650
new_tests                          29138
total_tests                        28763
total_tests_per_thousand           28763
new_tests_per_thousand             29138
new_tests_smoothed                 27217
new_tests_smoothed_per_thousand    27217
tests_per_case                     28636
positive_rate                      28252
tests_units                        26411
stringency_index                    7728
population                           264
population_density                  2283
median_age                          4833
aged_65_older                       5425
aged_70_older                       5040
gdp_per_capita                      5343
extreme_poverty                    18463
cardiovasc_death_rate               4818
diabetes_prevalence                 3419
female_smokers                     13427
male_smokers                       13822
handwashing_facilities             26127
hospital_beds_per_thousand          8646
life_expectancy                      822
human_development_index             6227
new_vaccinations                       0
total_vaccinations                     0
dtype: int64

In [18]:
df["country"] = (
    df["country"]
    .astype(str)
    .replace("nan", "Unknown")
    .fillna("Unknown")
)

df["country"].head()

0    Afghanistan
1    Afghanistan
2    Afghanistan
3    Afghanistan
4    Afghanistan
Name: country, dtype: object

In [19]:
numeric_columns = [
    "new_cases",
    "new_deaths",
    "new_vaccinations",
]

for col in numeric_columns:

    df[col] = pd.to_numeric(
        df[col],
        errors="coerce"
    ).fillna(0)

print("Numeric Conversion Completed")

Numeric Conversion Completed

In [20]:
df[numeric_columns].dtypes

new_cases           float64
new_deaths          float64
new_vaccinations      int64
dtype: object

In [21]:
duplicates = df.duplicated().sum()

print(f"Duplicate Rows Found: {duplicates}")

df.drop_duplicates(inplace=True)

print("Duplicates Removed Successfully")

Duplicate Rows Found: 0
Duplicates Removed Successfully

In [22]:
df.reset_index(
    drop=True,
    inplace=True
)

df.head()

  iso_code continent      country       date  total_cases  new_cases  new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  total_cases_per_million  new_cases_per_million  new_cases_smoothed_per_million  total_deaths_per_million  new_deaths_per_million  new_deaths_smoothed_per_million  new_tests  total_tests  total_tests_per_thousand  new_tests_per_thousand  new_tests_smoothed  new_tests_smoothed_per_thousand  tests_per_case  positive_rate tests_units  stringency_index  population  population_density  median_age  aged_65_older  aged_70_older  gdp_per_capita  extreme_poverty  cardiovasc_death_rate  diabetes_prevalence  female_smokers  male_smokers  handwashing_facilities  hospital_beds_per_thousand  life_expectancy  human_development_index  new_vaccinations  total_vaccinations
0      AFG      Asia  Afghanistan 2019-12-31          0.0        0.0                 NaN           0.0         0.0                  NaN                      0.0                    0.0                             NaN                       0.0                     0.0                              NaN        NaN          NaN                       NaN                     NaN                 NaN                              NaN             NaN            NaN         NaN               NaN  38928341.0              54.422        18.6          2.581          1.337        1803.987              NaN                597.029                 9.59             NaN           NaN                  37.746                         0.5            64.83                    0.498                 0                   0
1      AFG      Asia  Afghanistan 2020-01-01          0.0        0.0                 NaN           0.0         0.0                  NaN                      0.0                    0.0                             NaN                       0.0                     0.0                              NaN        NaN          NaN                       NaN                     NaN                 NaN                              NaN             NaN            NaN         NaN               0.0  38928341.0              54.422        18.6          2.581          1.337        1803.987              NaN                597.029                 9.59             NaN           NaN                  37.746                         0.5            64.83                    0.498                 0                   0
2      AFG      Asia  Afghanistan 2020-01-02          0.0        0.0                 NaN           0.0         0.0                  NaN                      0.0                    0.0                             NaN                       0.0                     0.0                              NaN        NaN          NaN                       NaN                     NaN                 NaN                              NaN             NaN            NaN         NaN               0.0  38928341.0              54.422        18.6          2.581          1.337        1803.987              NaN                597.029                 9.59             NaN           NaN                  37.746                         0.5            64.83                    0.498                 0                   0
3      AFG      Asia  Afghanistan 2020-01-03          0.0        0.0                 NaN           0.0         0.0                  NaN                      0.0                    0.0                             NaN                       0.0                     0.0                              NaN        NaN          NaN                       NaN                     NaN                 NaN                              NaN             NaN            NaN         NaN               0.0  38928341.0              54.422        18.6          2.581          1.337        1803.987              NaN                597.029                 9.59             NaN           NaN                  37.746                         0.5            64.83                    0.498                 0                   0
4      AFG      Asia  Afghanistan 2020-01-04          0.0        0.0                 NaN           0.0         0.0                  NaN                      0.0                    0.0                             NaN                       0.0                     0.0                              NaN        NaN          NaN                       NaN                     NaN                 NaN                              NaN             NaN            NaN         NaN               0.0  38928341.0              54.422        18.6          2.581          1.337        1803.987              NaN                597.029                 9.59             NaN           NaN                  37.746                         0.5            64.83                    0.498                 0                   0

In [23]:
for col in numeric_columns:

    negative_count = (df[col] < 0).sum()

    print(f"{col} Negative Values: {negative_count}")

new_cases Negative Values: 18
new_deaths Negative Values: 7
new_vaccinations Negative Values: 0

In [24]:
for col in numeric_columns:

    df[col] = np.where(
        df[col] < 0,
        0,
        df[col]
    )

print("Negative Values Cleaned")

Negative Values Cleaned

In [25]:
df["country"] = (
    df["country"]
    .str.strip()
    .str.title()
)

df["country"].head()

0    Afghanistan
1    Afghanistan
2    Afghanistan
3    Afghanistan
4    Afghanistan
Name: country, dtype: object

In [26]:
df.sort_values(
    by="date",
    inplace=True
)

df.head()

      iso_code continent      country       date  total_cases  new_cases  new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  total_cases_per_million  new_cases_per_million  new_cases_smoothed_per_million  total_deaths_per_million  new_deaths_per_million  new_deaths_smoothed_per_million  new_tests  total_tests  total_tests_per_thousand  new_tests_per_thousand  new_tests_smoothed  new_tests_smoothed_per_thousand  tests_per_case  positive_rate tests_units  stringency_index   population  population_density  median_age  aged_65_older  aged_70_older  gdp_per_capita  extreme_poverty  cardiovasc_death_rate  diabetes_prevalence  female_smokers  male_smokers  handwashing_facilities  hospital_beds_per_thousand  life_expectancy  human_development_index  new_vaccinations  total_vaccinations
0          AFG      Asia  Afghanistan 2019-12-31          0.0        0.0                 NaN           0.0         0.0                  NaN                      0.0                    0.0                             NaN                       0.0                     0.0                              NaN        NaN          NaN                       NaN                     NaN                 NaN                              NaN             NaN            NaN         NaN               NaN   38928341.0              54.422        18.6          2.581          1.337        1803.987              NaN                597.029                 9.59             NaN           NaN                  37.746                        0.50            64.83                    0.498                 0                   0
19752      IRL    Europe      Ireland 2019-12-31          0.0        0.0                 NaN           0.0         0.0                  NaN                      0.0                    0.0                             NaN                       0.0                     0.0                              NaN        NaN          NaN                       NaN                     NaN                 NaN                              NaN             NaN            NaN         NaN               NaN    4937796.0              69.874        38.7         13.928          8.678       67335.293              0.2                126.459                 3.28            23.0          25.7                     NaN                        2.96            82.30                    0.938                 0                   0
19488      IRQ      Asia         Iraq 2019-12-31          0.0        0.0                 NaN           0.0         0.0                  NaN                      0.0                    0.0                             NaN                       0.0                     0.0                              NaN        NaN          NaN                       NaN                     NaN                 NaN                              NaN             NaN            NaN         NaN               NaN   40222503.0              88.125        20.0          3.186          1.957       15663.986              2.5                218.612                 8.83             NaN           NaN                  94.576                        1.40            70.60                    0.685                 0                   0
19224      IRN      Asia         Iran 2019-12-31          0.0        0.0                 NaN           0.0         0.0                  NaN                      0.0                    0.0                             NaN                       0.0                     0.0                              NaN        NaN          NaN                       NaN                     NaN                 NaN                              NaN             NaN            NaN         NaN               NaN   83992953.0              49.831        32.4          5.440          3.182       19082.620              0.2                270.308                 9.59             0.8          21.1                     NaN                        1.50            76.68                    0.798                 0                   0
18960      IDN      Asia    Indonesia 2019-12-31          0.0        0.0                 NaN           0.0         0.0                  NaN                      0.0                    0.0                             NaN                       0.0                     0.0                              NaN        NaN          NaN                       NaN                     NaN                 NaN                              NaN             NaN            NaN         NaN               NaN  273523621.0             145.725        29.3          5.319          3.053       11188.744              5.7                342.864                 6.32             2.8          76.1                  64.204                        1.04            71.72                    0.694                 0                   0

In [27]:
df["total_cases_country"] = (
    df.groupby("country")["new_cases"]
    .cumsum()
)

df[
    [
        "country",
        "date",
        "new_cases",
        "total_cases_country"
    ]
].head()

           country       date  new_cases  total_cases_country
0      Afghanistan 2019-12-31        0.0                  0.0
19752      Ireland 2019-12-31        0.0                  0.0
19488         Iraq 2019-12-31        0.0                  0.0
19224         Iran 2019-12-31        0.0                  0.0
18960    Indonesia 2019-12-31        0.0                  0.0

In [28]:
df["total_deaths_country"] = (
    df.groupby("country")["new_deaths"]
    .cumsum()
)

df[
    [
        "country",
        "date",
        "new_deaths",
        "total_deaths_country"
    ]
].head()

           country       date  new_deaths  total_deaths_country
0      Afghanistan 2019-12-31         0.0                   0.0
19752      Ireland 2019-12-31         0.0                   0.0
19488         Iraq 2019-12-31         0.0                   0.0
19224         Iran 2019-12-31         0.0                   0.0
18960    Indonesia 2019-12-31         0.0                   0.0

In [29]:
df["total_vaccinations_country"] = (
    df.groupby("country")["total_vaccinations"]
    .cumsum()
)

df[
    [
        "country",
        "date",
        "total_vaccinations",
        "total_vaccinations_country"
    ]
].head()

           country       date  new_vaccinations  total_vaccinations_country
0      Afghanistan 2019-12-31                 0                           0
19752      Ireland 2019-12-31                 0                           0
19488         Iraq 2019-12-31                 0                           0
19224         Iran 2019-12-31                 0                           0
18960    Indonesia 2019-12-31                 0                           0

In [30]:
df["mortality_rate"] = np.where(
    df["total_cases_country"] > 0,
    (
        df["total_deaths_country"]
        / df["total_cases_country"]
    ) * 100,
    0
)

df[
    [
        "country",
        "mortality_rate"
    ]
].head()

           country  mortality_rate
0      Afghanistan             0.0
19752      Ireland             0.0
19488         Iraq             0.0
19224         Iran             0.0
18960    Indonesia             0.0

In [31]:
df["daily_growth_rate"] = (
    df.groupby("country")["new_cases"]
    .pct_change()
    .fillna(0)
) * 100

df[
    [
        "country",
        "daily_growth_rate"
    ]
].head()

           country  daily_growth_rate
0      Afghanistan                0.0
19752      Ireland                0.0
19488         Iraq                0.0
19224         Iran                0.0
18960    Indonesia                0.0

In [32]:
df["rolling_avg_cases"] = (
    df.groupby("country")["new_cases"]
    .transform(
        lambda x: x.rolling(
            window=7,
            min_periods=1
        ).mean()
    )
)

df[
    [
        "country",
        "rolling_avg_cases"
    ]
].head()

           country  rolling_avg_cases
0      Afghanistan                0.0
19752      Ireland                0.0
19488         Iraq                0.0
19224         Iran                0.0
18960    Indonesia                0.0

In [33]:
latest_date = df["date"].max()

latest_df = df[
    df["date"] == latest_date
]

hotspots = latest_df.sort_values(
    by="new_cases",
    ascending=False
).head(10)

hotspots[
    [
        "country",
        "new_cases",
        "new_deaths"
    ]
]

             country  new_cases  new_deaths
44520          World   309076.0      5947.0
18959          India    93337.0      1247.0
42376  United States    50209.0       956.0
6025          Brazil    39797.0       858.0
14636         France    13215.0       154.0
1683       Argentina    12701.0       262.0
9074        Colombia     6526.0       185.0
31940           Peru     6314.0       137.0
33573         Russia     5905.0       134.0
26596         Mexico     4841.0       624.0

In [34]:
df.isnull().sum()

iso_code                             264
continent                            528
country                                0
date                                   0
total_cases                          603
new_cases                              0
new_cases_smoothed                  1585
total_deaths                         603
new_deaths                             0
new_deaths_smoothed                 1585
total_cases_per_million              867
new_cases_per_million                867
new_cases_smoothed_per_million      1650
total_deaths_per_million             867
new_deaths_per_million               867
new_deaths_smoothed_per_million     1650
new_tests                          29138
total_tests                        28763
total_tests_per_thousand           28763
new_tests_per_thousand             29138
new_tests_smoothed                 27217
new_tests_smoothed_per_thousand    27217
tests_per_case                     28636
positive_rate                      28252
tests_units                        26411
stringency_index                    7728
population                           264
population_density                  2283
median_age                          4833
aged_65_older                       5425
aged_70_older                       5040
gdp_per_capita                      5343
extreme_poverty                    18463
cardiovasc_death_rate               4818
diabetes_prevalence                 3419
female_smokers                     13427
male_smokers                       13822
handwashing_facilities             26127
hospital_beds_per_thousand          8646
life_expectancy                      822
human_development_index             6227
new_vaccinations                       0
total_vaccinations                     0
total_cases_country                    0
total_deaths_country                   0
total_vaccinations_country             0
mortality_rate                         0
daily_growth_rate                      0
rolling_avg_cases                      0
dtype: int64

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 44785 entries, 0 to 44784
Data columns (total 49 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   iso_code                         44521 non-null  object
 1   continent                        44257 non-null  object
 2   country                          44785 non-null  object
 3   date                             44785 non-null  datetime64[ns]
 4   total_cases                      44182 non-null  float64
 5   new_cases                        44785 non-null  float64
 6   new_cases_smoothed               43200 non-null  float64
 7   total_deaths                     44182 non-null  float64
 8   new_deaths                       44785 non-null  float64
 9   new_deaths_smoothed              43200 non-null  float64
 10  total_cases_per_million          43918 non-null  float64
 11  new_cases_per_million            43918 non-null  float64
 12  new_cases_smoothed_per_million   43135 non-null  float64
 13  total_deaths_per_million         43918 non-null  float64
 14  new_deaths_per_million           43918 non-null  float64
 15  new_deaths_smoothed_per_million  43135 non-null  float64
 16  new_tests                        15647 non-null  float64
 17  total_tests                      16022 non-null  float64
 18  total_tests_per_thousand         16022 non-null  float64
 19  new_tests_per_thousand           15647 non-null  float64
 20  new_tests_smoothed               17568 non-null  float64
 21  new_tests_smoothed_per_thousand  17568 non-null  float64
 22  tests_per_case                   16149 non-null  float64
 23  positive_rate                    16533 non-null  float64
 24  tests_units                      18374 non-null  object
 25  stringency_index                 37057 non-null  float64
 26  population                       44521 non-null  float64
 27  population_density               42502 non-null  float64
 28  median_age                       39952 non-null  float64
 29  aged_65_older                    39360 non-null  float64
 30  aged_70_older                    39745 non-null  float64
 31  gdp_per_capita                   39442 non-null  float64
 32  extreme_poverty                  26322 non-null  float64
 33  cardiovasc_death_rate            39967 non-null  float64
 34  diabetes_prevalence              41366 non-null  float64
 35  female_smokers                   31358 non-null  float64
 36  male_smokers                     30963 non-null  float64
 37  handwashing_facilities           18658 non-null  float64
 38  hospital_beds_per_thousand       36139 non-null  float64
 39  life_expectancy                  43963 non-null  float64
 40  human_development_index          38558 non-null  float64
 41  new_vaccinations                 44785 non-null  int64
 42  total_vaccinations               44785 non-null  int64
 43  total_cases_country              44785 non-null  float64
 44  total_deaths_country             44785 non-null  float64
 45  total_vaccinations_country       44785 non-null  int64
 46  mortality_rate                   44785 non-null  float64
 47  daily_growth_rate                44785 non-null  float64
 48  rolling_avg_cases                44785 non-null  float64
dtypes: datetime64[ns](1), float64(41), int64(3), object(4)
memory usage: 17.1+ MB

In [36]:
df.to_csv(
    PROCESSED_DATA_PATH,
    index=False
)

print("Cleaned Dataset Saved Successfully")

print(PROCESSED_DATA_PATH)

Cleaned Dataset Saved Successfully
C:\Users\roshi\Downloads\covid19-data-analysis-visualization-main\covid19-data-analysis-visualization-main\data\processed\cleaned_covid_data.csv

In [37]:
cleaned_df = pd.read_csv(PROCESSED_DATA_PATH)

print(cleaned_df.shape)

cleaned_df.head()

(44785, 49)

  iso_code continent      country        date  total_cases  new_cases  new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  total_cases_per_million  new_cases_per_million  new_cases_smoothed_per_million  total_deaths_per_million  new_deaths_per_million  new_deaths_smoothed_per_million  new_tests  total_tests  total_tests_per_thousand  new_tests_per_thousand  new_tests_smoothed  new_tests_smoothed_per_thousand  tests_per_case  positive_rate tests_units  stringency_index   population  population_density  median_age  aged_65_older  aged_70_older  gdp_per_capita  extreme_poverty  cardiovasc_death_rate  diabetes_prevalence  female_smokers  male_smokers  handwashing_facilities  hospital_beds_per_thousand  life_expectancy  human_development_index  new_vaccinations  total_vaccinations  total_cases_country  total_deaths_country  total_vaccinations_country  mortality_rate  daily_growth_rate  rolling_avg_cases
0      AFG      Asia  Afghanistan  2019-12-31          0.0        0.0                 NaN           0.0         0.0                  NaN                      0.0                    0.0                             NaN                       0.0                     0.0                              NaN        NaN          NaN                       NaN                     NaN                 NaN                              NaN             NaN            NaN         NaN               NaN   38928341.0              54.422        18.6          2.581          1.337        1803.987              NaN                597.029                 9.59             NaN           NaN                  37.746                        0.50            64.83                    0.498                 0                   0                  0.0                   0.0                           0             0.0                0.0                0.0
1      IRL    Europe      Ireland  2019-12-31          0.0        0.0                 NaN           0.0         0.0                  NaN                      0.0                    0.0                             NaN                       0.0                     0.0                              NaN        NaN          NaN                       NaN                     NaN                 NaN                              NaN             NaN            NaN         NaN               NaN    4937796.0              69.874        38.7         13.928          8.678       67335.293              0.2                126.459                 3.28            23.0          25.7                     NaN                        2.96            82.30                    0.938                 0                   0                  0.0                   0.0                           0             0.0                0.0                0.0
2      IRQ      Asia         Iraq  2019-12-31          0.0        0.0                 NaN           0.0         0.0                  NaN                      0.0                    0.0                             NaN                       0.0                     0.0                              NaN        NaN          NaN                       NaN                     NaN                 NaN                              NaN             NaN            NaN         NaN               NaN   40222503.0              88.125        20.0          3.186          1.957       15663.986              2.5                218.612                 8.83             NaN           NaN                  94.576                        1.40            70.60                    0.685                 0                   0                  0.0                   0.0                           0             0.0                0.0                0.0
3      IRN      Asia         Iran  2019-12-31          0.0        0.0                 NaN           0.0         0.0                  NaN                      0.0                    0.0                             NaN                       0.0                     0.0                              NaN        NaN          NaN                       NaN                     NaN                 NaN                              NaN             NaN            NaN         NaN               NaN   83992953.0              49.831        32.4          5.440          3.182       19082.620              0.2                270.308                 9.59             0.8          21.1                     NaN                        1.50            76.68                    0.798                 0                   0                  0.0                   0.0                           0             0.0                0.0                0.0
4      IDN      Asia    Indonesia  2019-12-31          0.0        0.0                 NaN           0.0         0.0                  NaN                      0.0                    0.0                             NaN                       0.0                     0.0                              NaN        NaN          NaN                       NaN                     NaN                 NaN                              NaN             NaN            NaN         NaN               NaN  273523621.0             145.725        29.3          5.319          3.053       11188.744              5.7                342.864                 6.32             2.8          76.1                  64.204                        1.04            71.72                    0.694                 0                   0                  0.0                   0.0                           0             0.0                0.0                0.0

In [38]:
print("COVID-19 Data Cleaning Pipeline Completed Successfully")

COVID-19 Data Cleaning Pipeline Completed Successfully